# George Conde 03-02-2026
services:
  db:
    image: postgres:16-alpine
    container_name: etl_bi_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Edmonton
    ports:
      - "5432:5432"
    volumes:
      - etl_bi_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  adminer:
    image: adminer:4
    container_name: etl_bi_adminer
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  etl_bi_pgdata: